### PR TITLE
fix: automerge all but major bumps

### PR DESCRIPTION
**Pull request by dds**

### CODE REVIEW

**Comment by piperchester** [comment]
What do you think about starting with auto merge just for patch? And then increasing up to minor?

**Comment by dds** [comment]
> What do you think about starting with auto merge just for patch? And then increasing up to minor?

Yeah I'm still thinking about it.  I know we want this feature for many repos and I have more examples of where we want this than not.  But we have a lot of flexibility with how we set this (see the docs).  So I think I'd like to start here and see how it goes while testing repos slowly.

**Comment by dds** [comment]
> > What do you think about starting with auto merge just for patch? And then increasing up to minor?
> 
> Yeah I'm still thinking about it. I know we want this feature for many repos and I have more examples of where we want this than not. But we have a lot of flexibility with how we set this (see the docs). So I think I'd like to start here and see how it goes while testing repos slowly.

What do you think about it?

**Comment by piperchester** [comment]
> > > What do you think about starting with auto merge just for patch? And then increasing up to minor?
> > 
> > 
> > Yeah I'm still thinking about it. I know we want this feature for many repos and I have more examples of where we want this than not. But we have a lot of flexibility with how we set this (see the docs). So I think I'd like to start here and see how it goes while testing repos slowly.
> 
> What do you think about it @piperchester ?

I like the thinking 👍 personally I'm for the automerge. I suspect (could be wrong) that engs who may already be raising an eye brow won't be keen on automerge until they acclimate and Renovate accrues some trust. To your point though, easy to change 😃

**Pull request merged**
